services:
  - type: web
    name: fuel-tracker
    runtime: docker
    plan: free
    buildCommand: ./gradlew build -x test
    startCommand: java -jar build/libs/fuel-tracker-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod

